get http://localhost:3000/bands

###
get http://localhost:3000/bands/640bb16b6460fc60a033caf0

### valid band post

post http://localhost:3000/bands
Content-Type: application/json

{
    "name": "Pink Floyd",    
    "genre": ["Progressive Rock", "Psychedelic rock", "Classic Rock"],
    "website": "http://www.pinkfloyd.com",
    "recordCompany": "EMI",
    "groupMembers": ["Roger Waters", "David Gilmour", "Nick Mason", "Richard Wright", "Sid Barrett" ],
    "yearBandWasFormed": 1965
}

### invalid band post (changed website to .org)

post http://localhost:3000/bands
Content-Type: application/json

{
    "name": "Pink Floyd",    
    "genre": ["Progressive Rock", "Psychedelic rock", "Classic Rock"],
    "website": "http://www.pinkfloyd.org",
    "recordCompany": "EMI",
    "groupMembers": ["Roger Waters", "David Gilmour", "Nick Mason", "Richard Wright", "Sid Barrett" ],
    "yearBandWasFormed": 1965
}

###

put http://localhost:3000/bands/640bb16b6460fc60a033caf0
Content-Type: application/json

{
    "name": "Pink Floyd",    
    "genre": ["Classic Rock"],
    "website": "http://www.pinkfloydRocks.com",
    "recordCompany": "EMI",
    "groupMembers": ["Roger Waters", "David Gilmour", "Nick Mason", "Richard Wright", "Sid Barrett" ],
    "yearBandWasFormed": 1965
}

###

delete http://localhost:3000/bands/640bb4abfb80d0333916ad62

###

post http://localhost:3000/albums/640bc540e7e28bb42ab72ce8
Content-Type: application/json

{ 
  "title": "Wish You Were Here2",
  "releaseDate": "09/12/1975",
  "tracks": ["Shine On You Crazy Diamond, Pts. 1-5", "Welcome to the Machine","Have a Cigar (Ft. Roy Harper)", "Wish You Were Here","Shine On You Crazy Diamond, Pts. 6-9"],
  "rating": 5,
  "rating2": 5
}
